version: '3.8'
services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: vjfocus2
      POSTGRES_USER: vjfocus_user
      POSTGRES_PASSWORD: vjfocus_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: